# Generated by Django 2.2.6 on 2019-10-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
